/****** Object:  Table [dbo].[PA_FITT_Masks]    Script Date: 13/05/2022 15:11:06 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[PA_FITT_Masks](
	[ID] [numeric](18, 0) IDENTITY(1,1) NOT NULL,
	[MaskType] [nchar](20) NULL,
	[MaskName] [nchar](50) NULL,
 CONSTRAINT [PK_PA_FITT_Masks] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

